### ISSUE TITLE
Torch bug

### ISSUE THREAD

**Issue by andris155** [hankur/RestrictedCreative#55]
RestrictedCreative 2.0c-BUGGY
https://www.youtube.com/watch?v=Va7LQmlKL9A

**Comment by Prunt** [comment]
Couldn't reproduce the bug.

**Comment by andris155** [comment]
I tested. This protection work perfectly without FAWE. This is a FAWE plugin bug?

**Comment by hankur** [comment]
See the comment in #57.

**Comment by andris155** [comment]
Same problem with Asyncworldedit. Not fixed this. :(

**Comment by andris155** [comment]
https://www.spigotmc.org/resources/asyncworldedit-premium.9661/

**Comment by andris155** [comment]
I tested without other plugins not work this item protection.
